import Head from 'next/head'
const About = () => {
    return ( 
        <>
        <Head>
        <title>Staxo|About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem eius quia dignissimos magnam, excepturi esse perspiciatis beatae natus quod assumenda sed. Molestiae voluptas quos quod dolores neque similique dolorum libero!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem eius quia dignissimos magnam, excepturi esse perspiciatis beatae natus quod assumenda sed. Molestiae voluptas quos quod dolores neque similique dolorum libero!</p>
        
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem eius quia dignissimos magnam, excepturi esse perspiciatis beatae natus quod assumenda sed. Molestiae voluptas quos quod dolores neque similique dolorum libero!</p>
        
        </div>
        </>
     );
}
 
export default About;