import Head from 'next/head'
const Contact = () => {
    return ( 
        <>
        <Head>
        <title>Staxo|Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
            <h1>Contact Page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur impedit velit nisi obcaecati aspernatur repellat. Eligendi pariatur eveniet aspernatur quasi ea voluptatibus dolores molestias unde, cumque numquam, soluta voluptatum odit.</p>
            
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur impedit velit nisi obcaecati aspernatur repellat. Eligendi pariatur eveniet aspernatur quasi ea voluptatibus dolores molestias unde, cumque numquam, soluta voluptatum odit.</p>
            
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur impedit velit nisi obcaecati aspernatur repellat. Eligendi pariatur eveniet aspernatur quasi ea voluptatibus dolores molestias unde, cumque numquam, soluta voluptatum odit.</p>
        </div>
        </>
     );
}
 
export default Contact;