import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Staxo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className={styles.title}>Home</h1>
        <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus voluptates deleniti cumque? Ea sunt culpa atque fuga nostrum praesentium doloremque consectetur rem fugiat assumenda quibusdam autem expedita, qui dolorem placeat?</p>
        <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem eius quia dignissimos magnam, excepturi esse perspiciatis beatae natus quod assumenda sed. Molestiae voluptas quos quod dolores neque similique dolorum libero!</p>
        <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem eius quia dignissimos magnam, excepturi esse perspiciatis beatae natus quod assumenda sed. Molestiae voluptas quos quod dolores neque similique dolorum libero!</p>
        <Link href="/stax"><a className={styles.btn}>View Stax List</a></Link>
      </div>
    </div>
  )
}
