import Head from 'next/head';
export const getStaticPaths = async () => {
    const res = await fetch('https://jsonplaceholder.typicode.com/users');
    const data = await res.json();
  
    // map data to an array of path objects with params (id)
    const paths = data.map(stax => {
      return {
        params: { id: stax.id.toString() }
      }
    })
  
    return {
      paths,
      fallback: false
    }
  }
  
  export const getStaticProps = async (context) => {
    const id = context.params.id;
    const res = await fetch('https://jsonplaceholder.typicode.com/users/' + id);
    const data = await res.json();
  
    return {
      props: { stax: data }
    }
  }
  
  const Details = ({ stax }) => {
    return (
      <>
      <Head>
        <title>Staxo|{stax.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
      <div>
        <h1>{ stax.name }</h1>
        <p>{ stax.email }</p>
        <p>{ stax.website }</p>
        <p>{ stax.address.city }</p>
      </div>
      </>
    );
  }
  
  export default Details;