import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Stax.module.css';

export const getStaticProps = async () => {
    const res = await fetch('https://jsonplaceholder.typicode.com/users').then(data => data.json());
    return {
        props : { staxs: res }
    }
}

const Stax = ({staxs}) => {
   
    return ( 

        <>
        <Head>
        <title>Staxo|StaxList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <h1>StaxList</h1>
            {staxs.map(stax => (
                <Link key={stax.id}  href={'/stax/' + stax.id}>
                    <a className={styles.single}>
                        <h3>{stax.name}</h3>
                    </a>
                    
                </Link>
            ))}
            
        </div>
        </>
     );
}
 
export default Stax;